name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.2.1
        
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./
          file: ./.docker/Dockerfile
          tags: ghcr.io/zerozeroone-dev/yt-live.zerozeroone.dev:latest
          platforms: linux/amd64,linux/arm64
          push: true
